version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-manager-backend
    ports:
      - '8080:8000'
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - task-manager-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-manager-frontend
    ports:
      - '3000:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - task-manager-network

  db:
    image: mysql:8.0
    container_name: task-manager-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3308:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - task-manager-network

volumes:
  db-data:

networks:
  task-manager-network:
    driver: bridge
